### PR TITLE
Fixed grep and awk commands.

### PR DESCRIPTION
**Pull request by Breuls**
I noticed that due to differences between wat the grep and awk commands were assuming, and what the actual output from app/console was, the autocomplete didn't complete anything. This change fixes that.

I don't know if it's environment specific. This fix worked for me in a Vagrant box with Ubuntu 14.04, php 5.5.13, and a Symfony install that identifies itself as 2.7.0-DEV.

### CODE REVIEW

**Comment by jaytaph** [comment]
It seems fine on 2.5. There might be a change in the formatting. This could be easily fixed by using the xml command output, but it would requires additional dependencies and code.

I will check with 2.7 to see if a change in the format happened and if so, we might need to find a decent solution to make it more robust

**Comment by jaytaph** [comment]
Ok, figured it out.

The 2.5.x version uses 2 spaces, while the 2.7 only uses one space to separate "sections" from actual commands.

A better fix would be to check on 1 or more spaces, so it runs on both 2.5 and 2.7 (and presumably on 2.6 as well).

If I have time, I might create a .travis setup to test this automatically..

**Comment by jaytaph** [comment]
Using:

```
    cmds=` ${console} --no-ansi | sed -n -e '/^Available commands/,//p' | grep '^ ' | sed -e 's/^ \+//' | awk '{ print $1 }'`

    cmds=` ${console} ${COMP_WORDS[1]} --no-ansi --help | sed -n -e '/^Options/,/^$/p' | grep '^ ' | sed -e 's/^ \+//' | awk '{ print $1 }'`
```

would fix the issue for all versions. @breuls: do you want to fix this in your PR?

**Comment by Breuls** [comment]
Sure, but the autocomplete suggestions still end up in $2 when I use your modifications. 

After a little digging, it turns out that that's because I have the grep option -n on by default (through a bashrc alias), causing the line numbers to be the first item in every output line. This might be the case for more people, so I've chosen to enable it by default. That way, you can always be sure about the order of the awk output.

**Comment by jaytaph** [comment]
Seems to work. Thanks for the PR!

**Pull request merged**
